name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build docker image and run end-to-end tests
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code from github
      uses: actions/checkout@v3
    - name：Run end-to-end tests
      run: >
        docker compose --profile testing up
          --build
          --exit-code-from test-service
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: ${{ github.event_name == 'push' }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
